# base pre-built cross image
ARG CROSS_BASE_IMAGE
FROM $CROSS_BASE_IMAGE

ARG CROSS_DEB_ARCH

RUN echo $CROSS_BASE_IMAGE
RUN echo $CROSS_DEB_ARCH

# add our foreign architecture and install our dependencies
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN dpkg --add-architecture $CROSS_DEB_ARCH
RUN apt-get update && apt-get -y install libc6-dev:$CROSS_DEB_ARCH glibc-source:$CROSS_DEB_ARCH
