name: Docker Image CI

on:
  push:
    branches: ["main"]
    tags: ["v[0-9].[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: |
            linux/amd64
            linux/arm64

      - run: echo "FULL_IMAGE_TAG=$(git describe --tags --always)" >> $GITHUB_ENV

      - run: echo "IS_SAMVER_TAG=$(echo ${{ env.FULL_IMAGE_TAG }} | grep '^v[0-9]*\.[0-9]*\.[0-9]*$' -c)" >> $GITHUB_ENV

      - name: Create semver image tags
        if: ${{ env.IS_SAMVER_TAG == 1 }}
        run: |
          echo "MAJOR_IMAGE_TAG=$(echo ${{ env.FULL_IMAGE_TAG }} | cut -d . -f 1)" >> $GITHUB_ENV
          echo "MINOR_IMAGE_TAG=$(echo ${{ env.FULL_IMAGE_TAG }} | cut -d . -f 1,2)" >> $GITHUB_ENV

      - name: Install cross
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall cross --no-confirm

      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Compile
        run: |
          cross build --target x86_64-unknown-linux-gnu --release
          cross build --target aarch64-unknown-linux-gnu --release

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          context: .
          push: true
          tags: |
            ghcr.io/washed/pv-inv-bridge:latest
            ghcr.io/washed/pv-inv-bridge:${{ env.FULL_IMAGE_TAG }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push additional semver images
        uses: docker/build-push-action@v5
        if: ${{ env.IS_SAMVER_TAG == 1 }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          context: .
          push: true
          tags: |
            ghcr.io/washed/pv-inv-bridge:${{ env.MAJOR_IMAGE_TAG }}
            ghcr.io/washed/pv-inv-bridge:${{ env.MINOR_IMAGE_TAG }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max